version: '3'

services:
  web:
    image: nginx:1.13.5
    ports:
     - 8888:80
    volumes:
     - ./web:/usr/share/nginx/html:ro
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  api:
    image: node:8.6
    volumes:
     - ./api:/usr/src/app
     - ./data:/usr/src/data
    working_dir: /usr/src/app
    command: npm start
    ports:
     - 8000